services:
  backend:
    image: siriusgpb-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siriusgpb-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/config/.env
    volumes:
      - ./backend:/app